/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 28ce4d2afe98e929bec1af2f4ce1bb29)
interface __BaseEnv_Env {
	ATTACHMENTS: R2Bucket;
	DB: D1Database;
	ALLOWED_ORIGINS: "https://careersteps.net,https://www.careersteps.net";
	DISPLAY_TIME_ZONE: "America/Chicago";
	INVOICE_EMAIL_MODE: "live";
	INVOICE_EMAIL_FROM: "invoices@careersteps.net";
	ADMIN_PASSWORD: string;
	ADMIN_SESSION_SECRET: string;
	RESEND_API_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "DISPLAY_TIME_ZONE" | "INVOICE_EMAIL_MODE" | "INVOICE_EMAIL_FROM" | "ADMIN_PASSWORD" | "ADMIN_SESSION_SECRET" | "RESEND_API_KEY">> {}
}
