/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 58358990665b436dcdbc6d0325082b48)
interface __BaseEnv_Env {
	ATTACHMENTS: R2Bucket;
	DB: D1Database;
	ALLOWED_ORIGINS: "https://careersteps.net,https://www.careersteps.net";
	DISPLAY_TIME_ZONE: "America/Chicago";
	ADMIN_PASSWORD: string;
	ADMIN_SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "DISPLAY_TIME_ZONE" | "ADMIN_PASSWORD" | "ADMIN_SESSION_SECRET">> {}
}
